server:
  port: 8080
debug: true

spring:
  # Thymeleaf
  thymeleaf:
    encoding: UTF-8
    cache: false      # 热部署静态文件
    mode: HTML5       # 使用HTML5标准

  # DataSource
  datasource:
    url: jdbc:mysql://localhost/ssh_blog?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 112358
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA （@Entity表示使用JPA作为Repository接口代理实例）
  jpa:
    show-sql: true            #控制台是否显示sql语句
    hibernate:
      ddl-auto: update        #没有表新建，有表更新操作
#      ddl-auto: create-drop   #服务器重启后会自动将之前保存的数据全部删除掉，用于开发（！部署时这里需要修改）

  # ElasticSearch
  # TODO: ES的所有的配置项、作用及使用方法
  data:
    elasticsearch:
      cluster-nodes: localhost:9300   #默认9300是tcp通讯端口，9200是http协议的RESTful接口
